services:
  spring-app-db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  spring-app:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - spring-app-db
    environment:
      - "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
